[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm = "BzSik1LnEB5Tutpf5DXS4JpqWyFuZFJNFX2gF93jRPGW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
