[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_vault = "H2HyDQ9i7JhG9dyiSqMhNcSNL4hzLXq4mJCosX4mKQg4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
